# 04 numpy.array创建

In [16]:
import numpy

In [17]:
numpy.__version__

'1.16.2'

In [18]:
import numpy as np #给numpy起一个别名

In [19]:
np.__version__

'1.16.2'

## PythonList 特点
python的list对list中数据的类型不做任何限定，可以为数字、字符串、元组、列表等

In [20]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
L[5] = 'list'
L

[0, 1, 2, 3, 4, 'list', 6, 7, 8, 9]

## 采用array包可以固定类型

In [23]:
import array

In [24]:
arr = array.array('i', [i for i in range(10)]) # 'i'表示整形类型
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr[5] = 'list'

TypeError: an integer is required (got type str)

# numpy.array
提供矩阵和向量运算，更加方便

In [26]:
npayy = np.array([i for i in range(10)])

In [27]:
npayy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
npayy[5]     #采用索引取得其中的值

5

In [29]:
npayy[5] = 10

In [30]:
npayy

array([ 0,  1,  2,  3,  4, 10,  6,  7,  8,  9])

In [31]:
npayy[5] = 'Machine Learning' #只能用设定的类型赋值,否则报错

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [32]:
npayy.dtype   #查看默认设置的类型

dtype('int64')

In [34]:
npayy[5] = 5.0   #此时为浮点数，会自动转换为整数   
npayy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
npayy[5] = 3.14  #对浮点数会进行截位，只保留整数
npayy[6] = 3.8
npayy

array([0, 1, 2, 3, 4, 3, 3, 7, 8, 9])

In [37]:
npayy2 = np.array([1,2,3.0])     #只要在生成数组时有一个数为浮点型，则类型就会变为浮点型

In [38]:
npayy2.dtype

dtype('float64')

## 其他创建numpu.array的方式

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.zeros(10).dtype     #上面生成的数后面都有小数点，可知道其为浮点数

dtype('float64')

In [41]:
np.zeros((3,5), dtype=int)  #生成3行5列的矩阵，类型设置为整型

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [43]:
np.zeros(shape=(3,5), dtype=float) #行列的参数设置名称为shape，可省略，向上面一样直接设置,dtype不可省略

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
np.full((3,5), 666)    #创建指定数的矩阵,矩阵的类型根据指定数的类型进行默认设置，666为整型，666.0则为浮点型

#np.full(shape=(3,5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## arange（左闭右开）

#### 对于列表来说，随机数的步长只能是整数，不能是小数，但是对于numpy.arange,可以为小数

In [59]:
[i for i in range(1,10,2)]

[1, 3, 5, 7, 9]

In [60]:
[i for i in range(1, 10, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [61]:
np.arange(1, 10, 0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [62]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [63]:
np.arange(0, 10) #默认步长为1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.arange(10) #默认起始点为0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace（左右都闭）

In [65]:
np.linspace(0, 20, 10) #起始点为0，终止点为20， 等长的截出10个点 

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [66]:
np.linspace(0, 20, 11) #0 到 20 以2为步长，共有11个点

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

### 产生整数

In [68]:
np.random.randint(0, 10) #从0到10中随机取一个整数，取不到10

9

In [69]:
np.random.randint(0, 10, 10) #第三个参数表示取多少个随机数

array([1, 4, 5, 0, 5, 3, 6, 8, 8, 5])

In [70]:
np.random.randint(0, 10, (3,5))

array([[1, 8, 9, 3, 6],
       [7, 5, 8, 7, 5],
       [8, 9, 2, 7, 1]])

#### 为了避免参数之间的混淆，经常指明参数名称·

In [71]:
np.random.randint(0, 10, size=(3,5))

array([[1, 1, 3, 6, 2],
       [0, 4, 7, 6, 3],
       [1, 1, 8, 0, 0]])

#### 可以指定随机种子，保证产生相同的随机数

In [72]:
np.random.seed(666) #指定随机种子，相同的随机种子产生相同的随机数
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [74]:
np.random.seed(666)
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [75]:
np.random.seed(555)
np.random.randint(0, 10, size=(3, 5))

array([[9, 1, 4, 6, 6],
       [9, 0, 5, 0, 4],
       [6, 6, 5, 5, 0]])

### 产生浮点数

#### 产生均匀分布的随机数

In [76]:
np.random.random() #产生0到1之间的浮点数，取不到1, 0和1之间均匀分布

0.7988729487999761

In [77]:
np.random.random(10)

array([0.02267435, 0.64706719, 0.76878283, 0.8926319 , 0.82475265,
       0.56296713, 0.20633491, 0.51901626, 0.21315057, 0.70473498])

In [78]:
np.random.random((3,5))

array([[0.63847195, 0.71946907, 0.73001423, 0.81556019, 0.28162259],
       [0.07498055, 0.44002636, 0.87624011, 0.38040866, 0.38029327],
       [0.52024114, 0.99356318, 0.91477369, 0.24108958, 0.62209999]])

#### 产生高斯分布的随机数

In [81]:
np.random.normal(10, 100) #产生均值为10， 方差为100的高斯分布随机数

-21.320964363268683

In [82]:
np.random.normal(0, 1, size=(3, 5))

array([[ 0.40018891, -1.48591211,  1.01582316,  0.23602012, -0.77054601],
       [-1.12313093,  0.78717991,  0.60863098,  0.85421757,  0.08055337],
       [-0.5072582 , -0.57151417, -0.8640132 , -0.31930666,  1.73690473]])

## 对某个函数或者模块进行查询

In [83]:
np.random.normal? #第一种方法，在jupyter中

In [84]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap